import type { Metadata } from "next";
import { Footer, Layout, Navbar } from "nextra-theme-docs";
// import { Banner } from 'nextra/components'
import { getPageMap } from "nextra/page-map";
import "nextra-theme-docs/style.css";

export const metadata: Metadata = {
  title: "NextraDoc",
  description: "Generated by create next app and Nextra",
  // metadataBase: new URL("https://nextra.site"),
  applicationName: "NextraDoc",
  generator: "Next.js",
  appleWebApp: {
    title: "Nextra",
  },
  twitter: {
    site: "https://nextra.site",
  },
};

// const banner = <Banner storageKey="some-key">Currently working on this!</Banner>
const navbar = (
  <Navbar
    logo={
      <>
        <span className="_ms-2 max-md:_hidden _font-normal _text-gray-600">
          Nextra Doc
        </span>
      </>
    }
    // Next.js discord server
    // chatLink="https://discord.gg/hEM84NMkRv"

    // Github link
    projectLink="https://github.com/codingriri"
  ></Navbar>
);
const footer = (
  <Footer>
    MIT {new Date().getFullYear()} ©{" "}
    <a href="https://nextra.site" target="_blank">
      Nextra
    </a>
    .
  </Footer>
);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body>
        <Layout
          // banner={banner}
          navbar={navbar}
          pageMap={await getPageMap()}
          sidebar={{ autoCollapse: true }}
          docsRepositoryBase="https://github.com/codingriri"
          footer={footer}
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}
